### ISSUE TITLE
Document "tokenize"

### ISSUE THREAD

**Issue by VibhavSingh1** [353solutions/nlpy#9]
The `tokenize` function on `nlp/__init__.py` is not documented. Add a docstring to the function.

**Comment by tebeka** [comment]
It is documented - see https://github.com/353solutions/nlpy/blob/master/nlp/__init__.py#L31

Or any I missing something?

**Comment by VibhavSingh1** [comment]
Yes, it is.
I was just following your course so, raised it here by mistake. Also, thanks for the instructions,  they were all clear and it was a great learning experience throughout the course.

**Comment by tebeka** [comment]
Thanks!
